# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Kim Mingyu
title: Web BackEnd Engineer
email: rlaalsrb0466@naver.com
# email_title: Email (Email title override)
phone:
# phone_title: Phone (Phone title override)
website: https://min-nine.tistory.com
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username:
github_username:  MingyuRomeoKim
stackoverflow_username:
dribbble_username:
facebook_username:
flickr_username:
instagram_username: _dagyu
linkedin_username:
xing_username:
pinterest_username:
youtube_username:
orcid_username:
googlescholar_username:

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: /images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  웹/앱 서비스 백엔드 개발 및 언론 도메인 개발자로서의 다양한 경험이 있습니다. PHP, Java, Laravel, SpringBoot, MySQL, Redis, RabbitMQ, AWS, NCP, Git, Linux, Docker 등을 사용하여 프로덕션 서비스를 설계, 개발, 운영한 경험으로 확장성과 유지 보수성이 높은 백엔드 아키텍처와 패턴, 비지니스 로직 작성을 위해 언제나 고민하고 있습니다.
  <br/><br/>

  지금까지 최소 DAU 5천 이상, 최대 일 PV 1000만 이상 규모의 언론 매체 서비스에서 백엔드 개발 및 인프라 구축, DB 설계 등을 작업했습니다. 30개 이상의 웹 프로덕션 서비스를 개발하며 RestAPI, 기능 구현, 성능 최적화 작업, 레거시 시스템의 유지보수, 고도화를 통한 From PHP Legacy To Java Spring 마이그레이션 등 다양한 경험을 가지고 있습니다.
  <br/><br/>
  
  팀의 효율적인 업무 생산성을 위해 모두가 하고 싶어 하는 일과 기피하는 일을 가리지 않고 주도적으로 업무를 수행합니다. 조직의 업무 효율성을 높이고, 유연한 구조의 품질 높은 소프트웨어를 만들어 궁극적으로 사용자의 행복에 기여하고자 합니다. 지속적인 학습과 경험을 통해 업무 효율성을 극대화하고 시스템 가용성을 높이는 데 전념하고 있습니다.
  <br/><br/><br/>

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: (주)머니투데이 방송
        sub_title: 연구원
        caption: 2024.08 ~ present
        link: https://mtn.co.kr
        quote: >
          일 평균 수강자 3천명, 연 매출 400억 규모의 경제 및 주식 전문 방송 매체
        description: | # this will include new lines to allow paragraphs
          - 조회수 측정 데이터의 결점을 파악하여 데이터 무결성을 위한 뉴스 조회수 기능 개선 (RDB -> Redis & Batch)
          - 주식 방송 서비스 고도화 진행중 (Legacy PHP -> Spring Boot & NodeJS)
          - 다수의 CMS RestAPI 리팩토링 진행중 (각각 구성된 프로젝트 -> Spring Cloud를 활용한 Multi Module)
          <br/>

      - layout: left
        title: (주)머니투데이
        sub_title: 사원
        caption: 2022.04 ~ 2024.05
        link: https://mt.co.kr
        quote: >
          Google 1일 평균 노출수 10만, 일 평균 PV 400만 규모의 경제 전문지
        description: | # this will include new lines to allow paragraphs
          - 신규 웹 서비스 개발 진행 (2024 총선, PADO 매거진, Asia Artist Awards, 한국 기업가정신 등)
          - GitLab, AWS 환경에서 무중단 배포 및 운영 시스템 구축
          - 사이트 유지보수 및 신규 기능 개발 (머니투데이, 스타뉴스 등)
          - Mysql RDB 성능 튜닝 및 장애 대응 
          - 2년 연속 <mark>인사고과 A</mark> 취득
          <br/>

      - layout: left
        title: (주)경향신문사
        sub_title: 사원
        caption: 2018.11 ~ 2021.12
        link: https://khan.co.kr
        quote: >
          최대 일일 1000만 PV의 대한민국 메이저 진보 일간지
        description: | # this will include new lines to allow paragraphs
          - 신규 웹 서비스 개발 진행 (2020 도쿄 올림픽, 정동문화축제, 경향 뮤지컬 콩쿠르, 금융감독원 열린경제 등)
          - 사용자 맞춤형 기사 추천 서비스 설계 및 개발
          - 사이트 유지보수 및 신규 기능 개발 (경향신문, 비즈경향, 스포츠경향, 주간경향, 레이디경향 등)
          - Redis 서버 다운시 캐싱 미적용 문제를 해결하기 위해 CDN을 사용한 Json 캐싱 구현
          <br/><br/>

  - title: Skills
    layout: list
    content:
      - layout: left
        title: BackEnd
        sub_title:
        caption:
        link:
        quote: >
          Backend 프로덕션 서비스를 설계와 개발 및 운영하며 사용중이거나 사용했던 기술들입니다.
        description: | # this will include new lines to allow paragraphs
          - Language : PHP, JAVA, NodeJS
          - FrameWork : Laravel, Spring Boot, CodeIgniter
          - ORM : EloquentORM, QueryBuilder, JPA, QueryDSL, Hibernate 
          - PackageManager : Composer, Gradle                  
          <br/>

      - layout: left
        title: DevOps
        sub_title:
        caption:
        link:
        quote: >
          웹 및 앱 어플리케이션 프로덕션 서비스를 설계와 개발 및 운영하며 사용중이거나 사용했던 기술들입니다.
        description: | # this will include new lines to allow paragraphs                              
          - DB : Mysql, MariaDB, Redis, MongoDB
          - WebServer : Apache, Nginx, Tomcat, Netty
          - RemoteRepository : GitHub, GitLab, SourceCommit
          - Cloud : AWS, NCP
          - OS : Linux (CentOS, RedHat, Ubuntu)
          - CI/CD : GitLab Runner, Aws CodeDeploy, Ncp SourcePipeLine, Jenkins
          - ETC : Docker, RabbitMQ, Kafka          
          <br/>

      - layout: left
        title: FrontEnd
        sub_title:
        caption:
        link:
        quote: >
          Front 어플리케이션 프로덕션 서비스를 설계와 개발 및 운영하며 사용중이거나 사용했던 기술들입니다.
        description: | # this will include new lines to allow paragraphs                              
          - Language : JavaScript, Swift
          - FrameWork : NextJs, SwiftUI
          - Library : JQuery, ReactJS, VueJS
          - PackageManager : Npm, Yarn, CocoaPods
          <br/><br/>

  - title: Education & Certificate
    layout: list
    content:
      - layout: left
        title: 학사
        sub_title: 한국방송통신대학교 (졸업)
        caption: 2018.09 ~ 2021.08
        quote: >
          입학하기는 쉽지만 졸업률 극악의 자기주도학습형 대학교
        description: | # this will include new lines to allow paragraphs
          컴퓨터 과학과
          <br/>

      - layout: left
        title: 전문학사
        sub_title: 서일대학교 (중퇴)
        caption: 2016.03 ~ 2017.09
        quote: >
          서울특별시 중랑구에 위치한 2,3년제 전문 대학
        description: | # this will include new lines to allow paragraphs
          소프트웨어 공학과
          <br/>

      - layout: left
        title: 정보처리기사 취득
        sub_title: 한국산업인력공단
        caption: 2024.09
        quote: >

        description: | # this will include new lines to allow paragraphs
          <br/>

      - layout: left
        title: SQL 개발자 취득
        sub_title: 한국데이터베이스진흥협회
        caption: 2024.04
        quote: >

        description: | # this will include new lines to allow paragraphs
          <br/>

      - layout: left
        title: 네트워크관리사 2급 취득
        sub_title: 한국정보통신자격협회
        caption: 2021.07
        quote: >

        description: | # this will include new lines to allow paragraphs
          <br/><br/>

#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: left
#        border: weak  # Value of `weak` will display a weak border below this item. # Any
#                      # other value (or no value) means no border will be displayed
#        title: Project name
#        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#        link_text: Link Text
#        additional_links:
#          - title:  Github page for project (eg. sproogen/modern-resume-theme)
#            icon: fab fa-github
#            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#          - title:  Github page for project (eg. sproogen/modern-resume-theme)
#            icon: fab fa-github
#            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#        quote: >
#          Short overview of the project (optional)
#        description: | # this will include new lines to allow paragraphs
#          Description about the work on/with the project
#

# Footer
footer_show_references: true
references_title: Last Updated At 2024.11.02

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
