# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Kim Mingyu
title: Web BackEnd Engineer
email: rlaalsrb0466@naver.com
# email_title: Email (Email title override)
phone:
# phone_title: Phone (Phone title override)
website: https://min-nine.tistory.com
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: never

# Social links
twitter_username:
github_username:  MingyuRomeoKim
stackoverflow_username:
dribbble_username:
facebook_username:
flickr_username:
instagram_username: _dagyu
linkedin_username:
xing_username:
pinterest_username:
youtube_username:
orcid_username:
googlescholar_username:

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: /images/profile.png
about_content: | # this will include new lines to allow paragraphs
  웹/앱 서비스 백엔드 개발 및 언론 도메인 개발자로서의 다양한 경험이 있습니다. PHP, Java, Laravel, SpringBoot, MySQL, Redis, RabbitMQ, AWS, NCP, Git, Linux, Docker 등을 사용하여 프로덕션 서비스를 설계, 개발, 운영한 경험으로 확장성과 유지 보수성이 높은 백엔드 아키텍처와 패턴, 비지니스 로직 작성을 위해 언제나 고민하고 있습니다.
  <br/><br/>

  지금까지 최소 DAU 5천 이상, 최대 일 PV 1000만 이상 규모의 언론 매체 서비스에서 백엔드 개발 및 인프라 구축, DB 설계 등을 작업했습니다. 30개 이상의 웹 프로덕션 서비스를 개발하며 RestAPI, 기능 구현, 성능 최적화 작업, 레거시 시스템의 유지보수, 고도화를 통한 From PHP Legacy To Java Spring 마이그레이션 등 다양한 경험을 가지고 있습니다.
  <br/><br/>
  
  팀의 효율적인 업무 생산성을 위해 모두가 하고 싶어 하는 일과 기피하는 일을 가리지 않고 주도적으로 업무를 수행합니다. 조직의 업무 효율성을 높이고, 유연한 구조의 품질 높은 소프트웨어를 만들어 궁극적으로 사용자의 행복에 기여하고자 합니다. 지속적인 학습과 경험을 통해 업무 효율성을 극대화하고 시스템 가용성을 높이는 데 전념하고 있습니다.
  <br/><br/><br/>

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Bored
        sub_title: CTO
        caption: 2024.11 ~ present
        link: https://bored.co.kr
        quote: >
          혼자 어디까지 할 수 있는지 서버구축부터 모든 설계 및 구현을 홀로 진행하며 서비스를 운영중
        description: | # this will include new lines to allow paragraphs
          - Front : Php 8.3 + Laravel 11 + Blade + Livewire + BootstrapCSS + Redis
          - Back : Java 23 + Spring(Boot,Cloud,Security,Batch) + MSA + JPA + JPQL + QueryDSL + Gradle 
          - Infra : SKB(HomeServer) + Docker + Jenkins + GitHub + RabbitMQ + Redis + Mysql + Nginx        

      - layout: left
        title: (주)머니투데이 방송
        sub_title: 연구원
        caption: 2024.08 ~ present
        link: https://mtn.co.kr
        quote: >
          일 평균 수강자 3천명, 연 매출 400억 규모의 경제 및 주식 전문 방송 매체
        description: | # this will include new lines to allow paragraphs
          - 조회수 측정 데이터의 결점을 파악하여 데이터 무결성을 위한 뉴스 조회수 기능 개선 (RDB -> Redis & Batch)
          - 주식 방송 서비스 고도화 진행중 (Legacy PHP -> Spring Boot & NodeJS)
          - 다수의 CMS RestAPI 리팩토링 진행중 (각각 구성된 프로젝트 -> Spring Cloud, Multi Module 활용한 MSA 전환)
          - **RDB Query Tuning** (매 새벽 아무도 모르게 동작하던 엄청난 수의 JPA n+1 query -> bulk & batch 전환 등)
          - 이노페이, 헥토 세틀뱅크, KG 모빌리언스 등 **PG사 API**를 사용한 결제 및 환불 모듈 개발 (자체 수강권 발급 및 관리 등)
          <br/>

      - layout: left
        title: (주)머니투데이
        sub_title: 사원
        caption: 2022.04 ~ 2024.05
        link: https://mt.co.kr
        quote: >
          Google 1일 평균 노출수 10만, 일 평균 PV 400만 규모의 경제 전문지
        description: | # this will include new lines to allow paragraphs
          - 신규 웹 서비스 개발 진행 (2024 총선, PADO 매거진, Asia Artist Awards, 한국 기업가정신 등)
          - GitLab, AWS 환경에서 무중단 배포 및 운영 시스템 구축
          - 사이트 유지보수 및 신규 기능 개발 (머니투데이, 스타뉴스 등)
          - 스스로 Local 개발 환경 구축을 못 하는 사내 프론트 및 퍼블리셔들을 위한 **Docker Local 개발 환경 구축**
          - Mysql RDB 성능 튜닝 및 장애 대응 
          - 2년 연속 **인사고과 A** 취득
          <br/>

      - layout: left
        title: (주)경향신문사
        sub_title: 사원
        caption: 2018.11 ~ 2021.12
        link: https://khan.co.kr
        quote: >
          최대 일일 1000만 PV의 대한민국 메이저 진보 일간지
        description: | # this will include new lines to allow paragraphs
          - 신규 웹 서비스 개발 진행 (2020 도쿄 올림픽, 정동문화축제, 경향 뮤지컬 콩쿠르, 금융감독원 열린경제 등)
          - 사용자 맞춤형 기사 추천 서비스 설계 및 개발
          - 사이트 유지보수 및 신규 기능 개발 (경향신문, 비즈경향, 스포츠경향, 주간경향, 레이디경향 등)
          - Redis 서버 다운시 캐싱 미적용 문제를 해결하기 위해 CDN을 사용한 Json 캐싱 구현
          <br/><br/>

  - title: Skills
    layout: list
    content:
      - layout: left
        title: BackEnd
        sub_title:
        caption:
        link:
        quote: >
          Backend 프로덕션 서비스를 설계와 개발 및 운영하며 사용중이거나 사용했던 기술들입니다.
        description: | # this will include new lines to allow paragraphs
          - Language : PHP, JAVA, NodeJS
          - FrameWork : Laravel, Spring Boot, CodeIgniter
          - ORM : EloquentORM, QueryBuilder, JPA, QueryDSL, Hibernate 
          - PackageManager : Composer, Gradle                  
          <br/>

      - layout: left
        title: DevOps
        sub_title:
        caption:
        link:
        quote: >
          웹 및 앱 어플리케이션 프로덕션 서비스를 설계와 개발 및 운영하며 사용중이거나 사용했던 기술들입니다.
        description: | # this will include new lines to allow paragraphs                              
          - DB : Mysql, MariaDB, Redis, MongoDB
          - WebServer : Apache, Nginx, Tomcat, Netty
          - RemoteRepository : GitHub, GitLab, SourceCommit
          - Cloud : AWS, NCP
          - Container : Docker, Docker-compose
          - OS : Linux (CentOS, RedHat, Ubuntu)
          - CI/CD : GitLab Runner, Aws CodeDeploy, Ncp SourcePipeLine, Jenkins
          - Streaming : RabbitMQ, Kafka
          - Document : Scribe, Swagger
          - Collaboration Tool : Confluence(Jira, Wiki), RedMine, Slack, Naver Works
          <br/>

      - layout: left
        title: FrontEnd
        sub_title:
        caption:
        link:
        quote: >
          Front 어플리케이션 프로덕션 서비스를 설계와 개발 및 운영하며 사용중이거나 사용했던 기술들입니다.
        description: | # this will include new lines to allow paragraphs                              
          - Language : PHP, JavaScript, Swift
          - FrameWork : Laravel, CodeIgniter, NextJs, SwiftUI
          - Library : Blade Template, LiveWire, JQuery, ReactJS, VueJS
          - PackageManager : Composer, Npm, Yarn, CocoaPods
          <br/><br/>

  - title: Education & Certificate
    layout: list
    content:
      - layout: left
        title: 학사
        sub_title: 한국방송통신대학교 (졸업)
        caption: 2018.09 ~ 2021.08
        quote: >
          입학하기는 쉽지만 졸업률 극악의 자기주도학습형 대학교
        description: | # this will include new lines to allow paragraphs
          컴퓨터 과학과
          <br/>

      - layout: left
        title: 전문학사
        sub_title: 서일대학교 (중퇴)
        caption: 2016.03 ~ 2017.09
        quote: >
          서울특별시 중랑구에 위치한 2,3년제 전문 대학
        description: | # this will include new lines to allow paragraphs
          소프트웨어 공학과
          <br/>

      - layout: left
        border: weak
        title: 국비교육과정
        sub_title: 배움컴퓨터아트학원
        caption: 2015.07 ~ 2015.12
        quote: >
          서울특별시 종로구에 존재했던 국비교육기관
        description: | # this will include new lines to allow paragraphs
          Java, Spring, Mybatis, Html, Javascript, Css 등을 통한 웹 개발자 양성 과정
          <br/>

      - layout: left
        title: 정보처리기사
        sub_title: 한국산업인력공단
        caption: 2024.09
        quote: >

        description: | # this will include new lines to allow paragraphs
          자격증
          <br/>

      - layout: left
        title: SQL 개발자
        sub_title: 한국데이터베이스진흥협회
        caption: 2024.04
        quote: >

        description: | # this will include new lines to allow paragraphs
          자격증
          <br/>

      - layout: left
        title: 네트워크관리사 2급
        sub_title: 한국정보통신자격협회
        caption: 2021.07
        quote: >

        description: | # this will include new lines to allow paragraphs
          자격증
          <br/><br/>

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 머니투데이방송 기사 전송 Backend 개발 및 운영
        sub_title:
        caption:
        link: https://www.mtn.co.kr
        link_text: 2024.10.01 ~ 2024.10.21
        quote: >
          대신증권, 하나증권 등 nm개의 증권사에 실시간 기사 전송을 위한 프로그램
        description: | # this will include new lines to allow paragraphs
          - Web Socket을 사용한 실시간 기사 전송을 위한 프로그램 개발 및 운영.           
          <br/>

      - layout: left
        title: 머니투데이방송 RestAPI 고도화
        sub_title:
        caption:
        link: https://www.mtn.co.kr
        link_text: 2024.09.01 ~ 진행 중
        additional_links:
          - title:  Spring Gloud 연구 레포지토리
            icon: fab fa-github
            url: https://github.com/MingyuRomeoKim/spring-playground
        quote: >
          MTN, News, MTNW, MTNWPLUS, CMS 등 여러개로 분리 개발 및 운영되고 있는 RestAPI 프로젝트 고도화
        description: | # this will include new lines to allow paragraphs
          - Spring Cloud(Gateway, Eureka, OpenFeign 등)를 사용한 Multi Module 프로젝트로 고도화 작업 진행 중.
          - AccessKey, AccessToken, JWT Token 등 각양 각색의 사용되는 토큰을 JWT Token으로 통합 구축.
          - Spring Security WebSecurityConfigurerAdapter 방식(5.7 이하)에서 Filter Chain 방식(6.3.3)으로 업그레이드 작업 진행.
          <br/>

      - layout: left
        border: weak
        title: 주식명가 MTNWPLUS
        sub_title:
        caption:
        link: https://www.mtnw.co.kr/
        link_text: 2024.08.04 ~ 진행중
        #        additional_links:
        #          - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #            icon: fab fa-github
        #            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #          - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #            icon: fab fa-github
        #            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          MTN 머니투데이방송의 실시간 LIVE 전문가 증권방송 MTNW
        description: | # this will include new lines to allow paragraphs
          - 투자자문업 및 금융상품자문업 관련 법 변경으로 인한 MTNW -> MTNWPLUS 자문사 생성에 따른 데이터 및 사이트 이관
          - 중복 데이터 파악 및 테이블 재설계 및 데이터 마이그레이션에 따른 로직 변경
          - PG사 API를 사용한 결제 및 환불, 자체 수강권 발급 및 관리, 어드바이저 방송 관리 기능 등을 개발 및 운영
          <br/>

      - layout: left
        title: 2024 국회의원 총선
        sub_title:
        caption:
        link: https://www.mt.co.kr/election2024/
        link_text: 2024.03.15 ~ 2024.04.15
        quote: >
          머니투데이 2024 국회의원 총선 프로덕션 서비스 Backend 담당
        description: | # this will include new lines to allow paragraphs
          - 선거관리위원회 제공 XML 데이터를 이용한 실시간 투표 및 개표 API 개발 및 운영.
          - 총선 및 대선 시기에 급하게 레거시로 구현하던 관행에서 비지니스 로직화 및 문서화를 통한 하나의 선거 flow 구축.
          - 머니투데이 모든 서비스에 선거에 필요한 모든 데이터 제공하는 실시간 데이터 교환 프로그램 구현. 
          <br/>

      - layout: left
        title: 스타뉴스 Mobile Application 고도화
        sub_title:
        caption:
        link: https://apps.apple.com/kr/app/%EC%8A%A4%ED%83%80%EB%89%B4%EC%8A%A4-starnews/id448565570
        link_text: 2024.01.03 ~ 2024.03.18
        quote: >
          스타뉴스 Mobile Application 프로덕션 서비스 Backend 및 IOS 담당
        description: | # this will include new lines to allow paragraphs
          - 웹뷰에 툴바로 구성되어있는 단순했던 모바일 어플리케이션에서 Notification 기능을 포함한 별도의 설정 및 알림 페이지를 구축.
          - 기존 StoryBoard 형식의 단순 웹뷰 어플리케이션에서 SwiftUI를 도입하여 Hybrid Application으로 고도화.
          - 사일런스 알림 기능 구현을 통한 알림 매너 타임 기능을 구현하여 시도때도 없는 알림으로 부터 사용자 편의성 확보.
          <br/>

      - layout: left
        title: PADO 매거진
        sub_title:
        caption:
        link: https://www.pado.kr/
        link_text: 2023.02.01 ~ 2023.04.18
        quote: >
          롱리드 콘텐츠 기반의 국제적 이슈를 담당하는 프로덕션 서비스 Backend 담당
        description: | # this will include new lines to allow paragraphs
          - 프론트 및 퍼블리셔 인원의 부재로 유료 템플릿을 활용한 CMS 관리자 서비스 프론트 구현.        
          - GitLab Runner -> AWS S3, Code Deploy를 활용한 CI/CD 구현을 통한 효율적인 개발 프로세스 구축.
          - Scribe를 활용한 API 문서화를 통한 Front와의 불필요한 회의시간 단축으로 효율적인 WBS 기간 확립.
          - Json, Redis, RDB를 활용한 기사 임시 저장 및 불러오기 기능 구현하여 서비스 본질의 롱리드(숏폼의 반대)컨텐츠의 품질 향상.
          <br/>

      - layout: left
        title: AsiaArtistAwards 고도화
        sub_title:
        caption:
        link: https://www.asiaartistawards.com/
        link_text: 2022.10.25 ~ 2022.12.23
        quote: >
          국내 가수,배우 등 공인들의 뉴스 및 인기투표, 시상 프로덕션 서비스 고도화 작업 Backend 담당
        description: | # this will include new lines to allow paragraphs
          - 프로덕션 서비스가 운영되는 서버의 PHP 버전 업그레이드 (5.6 to 8.1)
          - 레거시로 구축되어있던 서비스 로직을 PHP FrameWork인 Laravel을 도입하여 코드 품질 향상.
          - GitLab Runner -> AWS S3, Code Deploy를 활용한 CI/CD 구현을 통한 효율적인 개발 프로세스 구축.
          <br/>

      - layout: left
        border: weak
        title: 재단법인 한국기업가정신
        sub_title:
        caption:
        link: https://www.efkorea.kr/
        link_text: 2022.08.08 ~ 2022.09.31
        quote: >
          국내 밴쳐기업의 투자유치를 위한 신규 프로덕션 서비스 BackEnd 및 FrontEnd 담당
        description: | # this will include new lines to allow paragraphs
          - 개발인력 부족으로 사용자 및 관리자 사이트 1인 구축 및 구현
          - 유료 템플릿을 커스텀하여 1개월이라는 짧은 시간 내에 30개 이상의 페이지 및 50개 이상의 기능을 구현.
          - 참가 기업 관련 정보의 암호화 및 파일의 보안을 위한 스토리지 서버 보안 설정 작업 진행.
          <br/>

      - layout: left
        title: 2021 도쿄올림픽
        link: https://sports.khan.co.kr/olympic/tokyo2020/index.html?www
        link_text: 2021.06.07 ~ 2021.08.13
        quote: >
          2021년 진행된 도쿄 올림픽 내용을 전문적으로 다루는 서비스 BackEnd 및 FrontEnd 담당
        description: | # this will include new lines to allow paragraphs
          - 개발인력 부족으로 사용자 및 관리자 사이트 1인 구축 및 구현
          - 기존 서비스의 HTML 및 CSS를 커스텀하여 2개월이라는 짧은 시간 내에 1일 최대 20만PV 규모의 서비스 제작.          
          <br/>

      - layout: left
        title: 경향신문 CMS 고도화
        sub_title:
        caption:
        link: https://cms.khan.co.kr
        link_text: 2020.11.29 ~ 2021.06.18
        quote: >
          30년 넘게 이용했던 CMS의 고도화 작업의 BackEnd 및 FrontEnd 담당
        description: | # this will include new lines to allow paragraphs
          - 살릴 수 있는 비지니스 로직과 없애야 하는 스파게티 및 에일리언 코드의 분석 및 문서화를 통해 전체 WBS 단축.
          - Laravel WebSocket을 활용한 CMS 동일 카테고리의 동시 사용자 작업 방지 구현.
          - 사용자(기자)들의 편의를 위한 다수의 기능 구현.
          - 로컬 개발 환경 없이 remote server에서 작업되던 팀 문화 개선을 위한 로컬 개발환경 구축, 그로 인한 개발 생산성 향상. 
          <br/>

      - layout: left
        title: 정동문화축제
        sub_title:
        caption:
        link: https://business.khan.co.kr/jeongdong
        link_text: 2020.10.26 ~ 2020.11.27
        quote: >
          서울시 주관 정동 문화축제 신규 웹 서비스로 BackEnd 및 FrontEnd 담당
        description: | # this will include new lines to allow paragraphs
          - 개발인력 부족으로 사용자 및 관리자 사이트 1인 구축 및 구현
          - Laravel 5.5버전을 사용하였는데 서버의 PHP 버전 문제로 사용할 수 없는 기능들이 많았고 이를 극복하기 위해 커스텀 하였음.
          - 하나의 라라벨 프로젝트에 3개의 서비스를 공존시켜달라는 요구사항을 토대로 route 분리.
          <br/>

      - layout: left
        title: 경향신문 고도화
        sub_title:
        caption:
        link: https://www.khan.co.kr
        link_text: 2020.06.01 ~ 2020.10.18
        quote: >
          노후화된 경향신문 사용자 서비스의 전체 개편 프로젝트에서 Backend 및 FrontEnd 담당
        description: | # this will include new lines to allow paragraphs
          - 살릴 수 있는 비지니스 로직과 없애야 하는 스파게티 및 에일리언 코드의 분석 및 문서화를 통해 전체 WBS 단축.
          - 무겁게 느껴졌던 Jquery 의존적인 팀 분위기를 Vanilla js로 전환시키기 위한 스터지 구성 및 Jquery 제거에 기여.
          - 로컬 개발 환경 없이 remote server에서 작업되던 팀 문화 개선을 위한 로컬 개발환경 구축, 그로 인한 개발 생산성 향상.
          - 순수 레거시에서 MVC 방식의 Modern PHP 첫 도입을 통한 프로젝트 파일트리 재구성.
          <br/>

      - layout: left
        title: 경향뮤지컬콩쿠르
        sub_title:
        caption:
        link: https://business.khan.co.kr/musical
        link_text: 2020.04.01 ~ 2020.05.31
        quote: >
          국내 최고의 뮤지컬 콩쿠르 접수 서비스로 BackEnd 및 FrontEnd 담당
        description: | # this will include new lines to allow paragraphs
          - 개발인력 부족으로 사용자 및 관리자 사이트 1인 구축 및 구현
          - Laravel 5.5버전을 사용하였는데 서버의 PHP 버전 문제로 사용할 수 없는 기능들이 많았고 이를 극복하기 위해 커스텀 하였음.
          - 하나의 라라벨 프로젝트에 3개의 서비스를 공존시켜달라는 요구사항을 토대로 route 분리.
          <br/>

      - layout: left
        title: 경향 마이페이지
        sub_title:
        caption:
        link: https://member.khan.co.kr/mypage/
        link_text: 2019.06.03 ~ 2019.10.25
        quote: >
          경향신문 웹 서비스에 기존에 없던 사용자 중심 기사 추천을 위한 마이페이지 서비스로 BackEnd 및 FrontEnd 담당
        description: | # this will include new lines to allow paragraphs
          - 사용자 맞춤형 기사 추천 알고리즘 구현
          - SNS 소셜 로그인 및 아이디 연동 서비스 구현, 회원 전환률 기존 대비 18% 상승
          - 북마크, 기자 구독 서비스 제공, 그로 인해 직전년 대비 월 최대 PV 12% 상승
          <br/>

      - layout: left
        title: 금융위원회 열린경제
        sub_title:
        caption:
        link: https://business.khan.co.kr/finance
        link_text: 2018.12.17 ~ 2019.02.15
        quote: >
          국내 최고의 뮤지컬 콩쿠르 접수 서비스로 BackEnd 및 FrontEnd 담당
        description: | # this will include new lines to allow paragraphs
          - 개발인력 부족으로 사용자 및 관리자 사이트 1인 구축 및 구현
          - 경향신문 서비스 최초로 Framework (Laravel)을 도입하여 제작한 프로덕션 서비스
          - Laravel 5.5버전을 사용하였는데 서버의 PHP 버전 문제로 사용할 수 없는 기능들이 많았고 이를 극복하기 위해 커스텀 하였음.
          <br/>
          

# Footer
footer_show_references: true
references_title: Last Updated At 2024.11.02

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
